-- This file is intentionally left blank.
-- The canvas_items table and its related logic have been deprecated and are no longer in use.
-- All canvas item data is now stored within the `history_present` column of the `projects` table.