-- Create the projects table
CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security for the projects table
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows users to see their own projects
CREATE POLICY "user_can_select_own_projects"
ON projects FOR SELECT
USING (auth.uid() = user_id);

-- Create a policy that allows users to insert their own projects
CREATE POLICY "user_can_insert_own_projects"
ON projects FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Create a policy that allows users to update their own projects
CREATE POLICY "user_can_update_own_projects"
ON projects FOR UPDATE
USING (auth.uid() = user_id);

-- Create a policy that allows users to delete their own projects
CREATE POLICY "user_can_delete_own_projects"
ON projects FOR DELETE
USING (auth.uid() = user_id);